# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://platformacrm.pl
title: platformaCRM
email: info@platformacrm.pl
description: > # "rozwi¹zania MRP / ERP / CRM
  dla dzia³u handlowego / zaopatrzenia / produkcji / magazynu / sprzeda¿y / serwisu"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap