# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://platformacrm.pl
title: Pomagamy największym firmom w swoich branżach
email: info@platformacrm.pl
description: > # "rozwiązania MRP / ERP / CRM dla działu handlowego / zaopatrzenia / produkcji / magazynu / sprzedaży / serwisu"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Umów się na prezentacje
    icon: glyphicon glyphicon-ok
    url: #contact
  - title: CRM
    icon: glyphicon glyphicon-ok
    url: #contact
  - title: ERP/MRP
    icon: glyphicon glyphicon-wrench
    url: #contact
