# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://platformacrm.pl
title: platformaCRM
email: info@platformacrm.pl
description: > # "rozwiązania MRP / ERP / CRM dla działu handlowego / zaopatrzenia / produkcji / magazynu / sprzedaży / serwisu"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: CRM
    url: http://platformacrm.pl
  - title: ERP
    url: http://platformacrm.pl
  - title: MRP
    url: http://platformacrm.pl
